---
output: word_document
---


```{r setup, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
# Load project configuration parameters, data, dico, and form
mainDir <- getwd()
  source(paste0(mainDir,"/code/0-config.R"), local=TRUE)
  data <- read_excel(path.to.data, sheet=sheet)


```

---
title: `r report_name`
author: `r paste0(author,", ", organisation)`
date: `r paste0(location,", ", Sys.Date())`
output: 
  word_document: 
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    toc: yes
    toc_depth: 2
---

***
***
# Executive summary and main findings

***
# Background Introduction

# Plotting Select_one questions



```{r bar_one, echo=FALSE, warning=FALSE, cache=FALSE, fig.width=7, fig.height=2}

#########################################################################################
## Produce graphs of all select_one questions
kobo_bar_one_print(data,dico)


```

# Plotting Select_multiple questions

```{r bar_multi, echo=FALSE, warning=FALSE, cache=FALSE, fig.width=7, fig.height=2}



#########################################################################################
## Produce graphs of all select_multiple questions
kobo_bar_multi_print(data,dico)

```


# Plotting numeric questions

```{r histogram, echo=FALSE, warning=FALSE, cache=FALSE, fig.width=7, fig.height=6}
#########################################################################################
## Produce histogramme for all numeric variable
#kobo_histo_print(data,dico)

```

# Plotting facetted analysis

```{r facet, echo=FALSE, warning=FALSE, cache=FALSE, fig.width=7, fig.height=8}

########################################################################################
### Produce faceted chart select_one

kobo_bar_one_facet_print(data,dico)
```
'''

```

```
